"""add budgets table

Revision ID: 947ee2f743f5
Revises: 
Create Date: 2026-03-03 16:52:11.274078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '947ee2f743f5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('amount', sa.Float(), nullable=True))
    op.add_column('budgets', sa.Column('month', sa.Integer(), nullable=True))
    op.add_column('budgets', sa.Column('year', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'budgets', ['user_id', 'month', 'year'])
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_constraint(None, 'budgets', type_='unique')
    op.drop_column('budgets', 'year')
    op.drop_column('budgets', 'month')
    op.drop_column('budgets', 'amount')
    op.drop_column('budgets', 'user_id')
    # ### end Alembic commands ###
